### ISSUE TITLE
Migrate jx controller to controller-runtime

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/lighthouse-jx-controller#40]
In the same spirit as https://github.com/jenkins-x/lighthouse/issues/933

There’s a lot of boilerplate code in the jx controller.

How about migrating the controller to controller-runtime ? This would simplify the implementation enormously and would be a lot easier to maintain.

**Comment by eddycharly** [comment]
@abayer i couldn't resist, i started working on it ;-)

**Comment by abayer** [comment]
I am not going to complain. =)
