### ISSUE TITLE
Is config agent and watcher used in the controller ?

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/lighthouse-jx-controller#45]
https://github.com/jenkins-x/lighthouse-jx-controller/blob/5ebf5c01c83d13433a81ef3c6211ac0a8251fdb7/pkg/engines/jx/controller.go#L90-L115

Is config agent and watcher used ?
They are instantiated but they don't seem to be used and i'm not sure if they are needed.

**Comment by abayer** [comment]
Nope, looks like I just forgot to remove it.
